
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifnnpzjvypzzbcusilwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlmbm5wemp2eXB6emJjdXNpbHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzEzMDUsImV4cCI6MjA1ODg0NzMwNX0.qg2Px6ZWJy6PPMOspqG54nVXnugCetIO8D8QuVpV9pI";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
